### ISSUE TITLE
📍 EPIC : Page Explorer

### ISSUE THREAD

**Issue by oncletom** [dtc-innovation/dataviz-finances-montreuil#54]
[<img width="503" alt="image" src="https://user-images.githubusercontent.com/138627/53397727-2637f080-39a8-11e9-9f66-0af9003599de.png">](https://www.figma.com/file/NKgSOd1pwalNQPx2LTTy5sTx/Dataviz-Montreuil?node-id=149%3A1165)

- [x] La page d'accueil devient la page Explorer #50
- [x] Le compte est représenté par des donuts recettes et dépenses #51
- [x] Les familles de fonctions sont représentées sous forme de Bubble Chart #52
- [ ] Générer les formules d'agrégation à partir du fichier Excel des formules #47 
- [x] Le survol d'une bulle affiche une infobulle #53
